<a href="https://colab.research.google.com/github/Muyiiwaa/learn-EDA/blob/master/Data_Wrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Data Wrangling with Pandas and Numpy

In [1]:
import numpy as np
import pandas as pd

In [3]:
salary = [200,350,400,500]

type(salary[0])

int

In [7]:
# convert salary to a numpy array

salary2 = np.array(salary)

print(type(salary2))

salary2.dtype

<class 'numpy.ndarray'>

dtype('int64')

In [11]:
# How to create dataframes in  pandas

# through list of lists

students_list = [
    ['bayo',23,'m','osun'],
    ['tobi',13,'m','lagos'],
    ['abdul',23,'m','oyo'],
    ['folake',43,'f','lagos'],
    ['esther',23,'f','osun'],
]

# cnverting to a numpy array
students_array = np.array(students_list)
students_array

# create a pandas dataframe

students_data = pd.DataFrame(data=students_list, columns = ['name','age','gender','state'])
students_data

     name  age gender  state
0    bayo   23      m   osun
1    tobi   13      m  lagos
2   abdul   23      m    oyo
3  folake   43      f  lagos
4  esther   23      f   osun

In [12]:
# creating data from dictionaries


clubs = {
    'name': ['utd','chelsea','arsenal','kano pillars','madrid'],
    'city' : ['manchester','london','london','kano','madrid'],
    'country': ['uk','uk','uk','nigeria','spain']
}

clubs_data = pd.DataFrame(data = clubs)
clubs_data

           name        city  country
0           utd  manchester       uk
1       chelsea      london       uk
2       arsenal      london       uk
3  kano pillars        kano  nigeria
4        madrid      madrid    spain

# Assignments

1. generate any dataset of your choice using list of lists and also dictionaries
2. import any dataset of your choice and use all the 12 methods we used in class on the dataset
3. Go to pandas doc and use any 5 new methods that we have not touched in class on your dataset

* get_data: https://www.kaggle.com/
* pandas_doc: https://pandas.pydata.org/docs/user_guide/10min.html

### Importing data from a local file

In [13]:
# import csv file

data = pd.read_csv('cleaned_marketing.csv')
data

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138,0,0,2012-09-04,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344,1,1,2014-03-08,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613,0,0,2013-08-21,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646,1,0,2014-02-10,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293,1,0,2014-01-19,94,173,...,5,0,0,0,0,0,0,3,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,Graduation,Married,61223,0,1,2013-06-13,46,709,...,5,0,0,0,0,0,0,3,11,0
2236,4001,1946,PhD,Together,64014,2,1,2014-06-10,56,406,...,7,0,0,0,1,0,0,3,11,0
2237,7270,1981,Graduation,Divorced,56981,0,0,2014-01-25,91,908,...,6,0,1,0,0,0,0,3,11,0
2238,8235,1956,Master,Together,69245,0,1,2014-01-24,8,428,...,3,0,0,0,0,0,0,3,11,0
2239,9405,1954,PhD,Married,52869,1,1,2012-10-15,40,84,...,7,0,0,0,0,0,0,3,11,1

In [14]:
# upload an excel file

spam_df = pd.read_excel('spam.xlsx')
spam_df

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

## COMMON PANDAS METHODS

1. head -- first n rows
2. tail -- last n rows
3. shape -- get no of rows and columns
4. astype -- converts datatypes
5. describe -- for getting summary statistics
6. drop -- dropping rows or columns
7. group by -- for grouping
8. isnull.sum -- for checking null values
9. dropna -- for dropping null values
10. apply -- for fuction calling
11. reset_index -- for reseting index
12. value_counts -- for counting unique values and their frequency

In [17]:
# head method

data.head(4)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138,0,0,2012-09-04,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344,1,1,2014-03-08,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613,0,0,2013-08-21,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646,1,0,2014-02-10,26,11,...,6,0,0,0,0,0,0,3,11,0

In [18]:
# tail method

data.tail(6)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
2234,8372,1974,Graduation,Married,34421,1,0,2013-07-01,81,3,...,7,0,0,0,0,0,0,3,11,0
2235,10870,1967,Graduation,Married,61223,0,1,2013-06-13,46,709,...,5,0,0,0,0,0,0,3,11,0
2236,4001,1946,PhD,Together,64014,2,1,2014-06-10,56,406,...,7,0,0,0,1,0,0,3,11,0
2237,7270,1981,Graduation,Divorced,56981,0,0,2014-01-25,91,908,...,6,0,1,0,0,0,0,3,11,0
2238,8235,1956,Master,Together,69245,0,1,2014-01-24,8,428,...,3,0,0,0,0,0,0,3,11,0
2239,9405,1954,PhD,Married,52869,1,1,2012-10-15,40,84,...,7,0,0,0,0,0,0,3,11,1

In [19]:
# .shape attribute

data.shape

(2240, 29)

In [26]:
# info method

data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2216 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2216 non-null   int64
 1   Year_Birth           2216 non-null   int64
 2   Education            2216 non-null   object
 3   Marital_Status       2216 non-null   object
 4   Income               2216 non-null   int64
 5   Kidhome              2216 non-null   int64
 6   Teenhome             2216 non-null   int64
 7   Dt_Customer          2216 non-null   datetime64[ns]
 8   Recency              2216 non-null   int64
 9   MntWines             2216 non-null   int64
 10  MntFruits            2216 non-null   int64
 11  MntMeatProducts      2216 non-null   int64
 12  MntFishProducts      2216 non-null   int64
 13  MntSweetProducts     2216 non-null   int64
 14  MntGoldProds         2216 non-null   int64
 15  NumDealsPurchases    2216 non-null   int64
 16  NumWebPurchases      2216 non-null   int64
 17  NumCatalogPurchases  2216 non-null   int64
 18  NumStorePurchases    2216 non-null   int64
 19  NumWebVisitsMonth    2216 non-null   int64
 20  AcceptedCmp3         2216 non-null   int64
 21  AcceptedCmp4         2216 non-null   int64
 22  AcceptedCmp5         2216 non-null   int64
 23  AcceptedCmp1         2216 non-null   int64
 24  AcceptedCmp2         2216 non-null   int64
 25  Complain             2216 non-null   int64
 26  Z_CostContact        2216 non-null   int64
 27  Z_Revenue            2216 non-null   int64
 28  Response             2216 non-null   int64
dtypes: datetime64[ns](1), int64(26), object(2)
memory usage: 519.4+ KB

In [24]:
data = data[data['Income'] != ' ']

In [25]:
# .astype method

data = data.astype(
    {'Income':'int64',
     'Dt_Customer':'datetime64[ns]'}
)

In [29]:
# describe method

data[['Income','Recency']].describe()

              Income      Recency
count    2216.000000  2216.000000
mean    52247.251354    49.012635
std     25173.076661    28.948352
min      1730.000000     0.000000
25%     35303.000000    24.000000
50%     51381.500000    49.000000
75%     68522.000000    74.000000
max    666666.000000    99.000000

In [34]:
data.drop([0,1,2], inplace = True)

In [36]:
# rest_index

data.reset_index(inplace = True, drop = True)

In [38]:
# dropping columns

data.drop(['ID','Year_Birth'], axis = 1, inplace = True)

In [42]:
data[['Income','Education']].groupby(['Education']).mean()

                  Income
Education
2n Cycle    47633.190000
Basic       20306.259259
Graduation  52704.260557
Master      52917.534247
PhD         56145.313929

In [47]:
data['Marital_Status'].value_counts()

Marital_Status
Married     857
Together    572
Single      476
Divorced    232
Widow        76
Name: count, dtype: int64

In [46]:
# row editing with list comprehension

data['Marital_Status'] = ['Single' if x in ['Alone','Absurd','YOLO','Single'] else x for x in data['Marital_Status']]

In [48]:
data.isnull().sum()

Education              0
Marital_Status         0
Income                 0
Kidhome                0
Teenhome               0
Dt_Customer            0
Recency                0
MntWines               0
MntFruits              0
MntMeatProducts        0
MntFishProducts        0
MntSweetProducts       0
MntGoldProds           0
NumDealsPurchases      0
NumWebPurchases        0
NumCatalogPurchases    0
NumStorePurchases      0
NumWebVisitsMonth      0
AcceptedCmp3           0
AcceptedCmp4           0
AcceptedCmp5           0
AcceptedCmp1           0
AcceptedCmp2           0
Complain               0
Z_CostContact          0
Z_Revenue              0
Response               0
dtype: int64

In [52]:
spam_df.isnull().sum()

v1            0
v2            0
Unnamed: 2    0
Unnamed: 3    0
Unnamed: 4    0
dtype: int64

In [51]:
spam_df.dropna(inplace = True)

In [55]:
# create the tax function
def get_tax(x):
  tax = x * 0.04
  return tax

# call the function using .apply
data['income_tax'] = data['Income'].apply(get_tax)

In [56]:
data

,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,MntMeatProducts,...,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response,income_tax
0,Graduation,Together,26646,1,0,2014-02-10,26,11,4,20,...,0,0,0,0,0,0,3,11,0,1065.84
1,PhD,Married,58293,1,0,2014-01-19,94,173,43,118,...,0,0,0,0,0,0,3,11,0,2331.72
2,Master,Together,62513,0,1,2013-09-09,16,520,42,98,...,0,0,0,0,0,0,3,11,0,2500.52
3,Graduation,Divorced,55635,0,1,2012-11-13,34,235,65,164,...,0,0,0,0,0,0,3,11,0,2225.40
4,PhD,Married,33454,1,0,2013-05-08,32,76,10,56,...,0,0,0,0,0,0,3,11,0,1338.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2208,Graduation,Married,61223,0,1,2013-06-13,46,709,43,182,...,0,0,0,0,0,0,3,11,0,2448.92
2209,PhD,Together,64014,2,1,2014-06-10,56,406,0,30,...,0,0,0,1,0,0,3,11,0,2560.56
2210,Graduation,Divorced,56981,0,0,2014-01-25,91,908,48,217,...,0,1,0,0,0,0,3,11,0,2279.24
2211,Master,Together,69245,0,1,2014-01-24,8,428,30,214,...,0,0,0,0,0,0,3,11,0,2769.80
2212,PhD,Married,52869,1,1,2012-10-15,40,84,3,61,...,0,0,0,0,0,0,3,11,1,2114.76